### ISSUE TITLE
Choir: steps for deployment

### ISSUE THREAD

**Issue by Gelassen** [DenysMoiseienko/telegramBot#1]
It is a good practice to have description of steps to deploy the application. (just as an [example](https://github.com/Gelassen/skills-market))

Could you please to add it to your project? 

Issues that I faced with are: 
- IDE has crashed when I opened the app (it appears that it is a known issue on Jetbrains side, but it would be good to know system environment you run your project, e.g. IDE name and its version, OS and its version, JDK etc)
- definition of global variables (it would be good to have an option to run locally as well as on Heroku which means read this variables from file in case of local launch)
- spring boot configuration (there are some dependencies IDE console shows has remain unmatched)

**Comment by DenysMoiseienko** [comment]
Hello, @Gelassen. Thank you for opening the issue.
I have updated README.md, and I hope that now everything is clear.
What about my system environment. I use IntelliJ IDEA 2020.2.4 (Ultimate Edition) and Mac OS X 10.14.6 x86_64
